{% set name = "nix" %}
{% set version = "2.3.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://nixos.org/releases/nix/nix-{{ version }}/nix-{{ version }}.tar.xz
  sha256: 37e3310a55fde1e50e7d4321d29b9180d1e9d7af9c8d211db6a667e6ee4eb410

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports:
    - libxslt
    - libxml2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make
  host:
    - openssl
    - brotli
    - bzip2
    - xz
    - curl
    - sqlite
    - boost-cpp
    - editline
    - libxml2
    - libxslt
    - bison
    - flex
    - libseccomp  # [linux]
  run:
    - brotli
    - boost-cpp
    - libcurl
    - curl
    - editline

test:
  commands:
    - nix --help

about:
  home: https://nixos.org/nix/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: The Purely Functional Package Manager
  description: |
    Nix is a powerful package manager for Linux and other Unix systems
    that makes package management reliable and reproducible. It provides
    atomic upgrades and rollbacks, side-by-side installation of multiple
    versions of a package, multi-user package management and easy setup
    of build environments.
  doc_url: https://nixos.org/nix/manual/
  dev_url: https://github.com/NixOS/nix

extra:
  recipe-maintainers:
    - scopatz
